version: "3.1"
services:
  islasgeci:
    build:
      context: .
      dockerfile: Dockerfile
    image: islasgeci/referee_cat_recognition:latest
    command: bash
    volumes:
      - $PWD:/workdir
